name: flutter_taozugong_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # http请求
  dio: 2.1.7
  # 图片轮播swiper
  flutter_swiper: 1.1.6
  # 下拉刷新和上拉加载
  flutter_easyrefresh: 1.2.7
  # 分类tab
  # bubble_tab_indicator: 0.1.4
  # 状态管理框架
  # provide: 1.0.2
  # 路由
  fluro: 1.4.0
  #SQL数据库插件
  #sqflite: 1.1.5
  # 提示
  oktoast: ^2.1.8
  # url 启动
  url_launcher: 5.0.2
  # 适配不同屏幕设备
  flutter_screenutil: 0.5.2
  #  shared_preferences: 0.5.3+1
  #flutter_html: 0.10.1
  # 状态管理
  scoped_model: 1.0.1
  #event_bus: 1.1.0
  #connectivity: 0.4.3+1

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.5
  # Flutter UI组件库 https://github.com/flutterchina/flukit.
  #flukit: ^1.0.0
  #WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  # webview_flutter: 0.3.7+1
  webview_flutter: 0.2.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1
  #flutter_webview_plugin: 0.3.5
  crypto: ^2.0.6
  city_pickers: ^0.1.16
  image_picker: ^0.4.10
  # 支付宝支付SDK
  tobias: ^1.0.0+1
  #sy_flutter_alipay: 0.2.1
  #flutter_alipay: ^0.1.0
  #alipay_me: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/images/common/
    - assets/images/user/
    - assets/images/order/
    - assets/images/login/
    - assets/images/ordertail/
    - assets/images/address/
    - assets/images/user/user-bg.png
    - assets/images/user/see.png
    - assets/images/user/del.png
    - assets/images/arrow_right.png
    - assets/images/me_vip.png
    - assets/images/me_buy.png
    - assets/images/me_gift.png
    - assets/images/me_date.png
    - assets/images/me_theme.png
    - assets/images/me_night.png
    - assets/images/me_wallet.png
    - assets/images/me_record.png
    - assets/images/me_coupon.png
    - assets/images/me_action.png
    - assets/images/me_setting.png
    - assets/images/me_comment.png
    - assets/images/me_feedback.png
    - assets/images/me_favorite.png
    - assets/images/be-pay.png
    - assets/images/be-received.png
    - assets/images/be-rent.png
    - assets/images/be-shipped.png
    - assets/images/coupon/noCoupon.jpg
    - assets/images/coupon/used.jpg
    - assets/images/coupon/expired.jpg
    - assets/images/common/addPhoto.png
    - assets/images/ordertail/guanbi.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
