class Autogenerated {
  num code;
  String msg;
  String subMsg;
  Data data;

  Autogenerated({this.code, this.msg, this.subMsg, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    msg = json['msg'];
    subMsg = json['subMsg'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['msg'] = this.msg;
    data['subMsg'] = this.subMsg;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

class Data {
  String no;
  String video;
  List<String> pictureList;
  num minPrice;
  num maxPrice;
  num officialPrice;
  String unit;
  String name;
  String brief;
  List<SpecificationVOList> specificationVOList;
  List<String> detail;
  List<String> parameterList;
  List<String> afterSaleList;
  num isFace;
  num isAuthentication;
  num businessType;
  List<String> goodsLabelList;
  String alipayCode;

  Data(
      {this.no,
      this.video,
      this.pictureList,
      this.minPrice,
      this.maxPrice,
      this.officialPrice,
      this.unit,
      this.name,
      this.brief,
      this.specificationVOList,
      this.detail,
      this.parameterList,
      this.afterSaleList,
      this.isFace,
      this.isAuthentication,
      this.businessType,
      this.goodsLabelList,
      this.alipayCode});

  Data.fromJson(Map<String, dynamic> json) {
    no = json['no'];
    video = json['video'];
    pictureList = json['pictureList'].cast<String>();
    minPrice = json['minPrice'];
    maxPrice = json['maxPrice'];
    officialPrice = json['officialPrice'];
    unit = json['unit'];
    name = json['name'];
    brief = json['brief'];
    if (json['specificationVOList'] != null) {
      specificationVOList = new List<SpecificationVOList>();
      json['specificationVOList'].forEach((v) {
        specificationVOList.add(new SpecificationVOList.fromJson(v));
      });
    }
    detail = json['detail'].cast<String>();
    parameterList = json['parameterList'].cast<String>();
    afterSaleList = json['afterSaleList'].cast<String>();
    isFace = json['isFace'];
    isAuthentication = json['isAuthentication'];
    businessType = json['businessType'];
    goodsLabelList = json['goodsLabelList'].cast<String>();
    alipayCode = json['alipayCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['no'] = this.no;
    data['video'] = this.video;
    data['pictureList'] = this.pictureList;
    data['minPrice'] = this.minPrice;
    data['maxPrice'] = this.maxPrice;
    data['officialPrice'] = this.officialPrice;
    data['unit'] = this.unit;
    data['name'] = this.name;
    data['brief'] = this.brief;
    if (this.specificationVOList != null) {
      data['specificationVOList'] =
          this.specificationVOList.map((v) => v.toJson()).toList();
    }
    data['detail'] = this.detail;
    data['parameterList'] = this.parameterList;
    data['afterSaleList'] = this.afterSaleList;
    data['isFace'] = this.isFace;
    data['isAuthentication'] = this.isAuthentication;
    data['businessType'] = this.businessType;
    data['goodsLabelList'] = this.goodsLabelList;
    data['alipayCode'] = this.alipayCode;
    return data;
  }
}

class SpecificationVOList {
  SpecificationKeyVO specificationKeyVO;
  List<SpecificationValueVOList> specificationValueVOList;

  SpecificationVOList({this.specificationKeyVO, this.specificationValueVOList});

  SpecificationVOList.fromJson(Map<String, dynamic> json) {
    specificationKeyVO = json['specificationKeyVO'] != null
        ? new SpecificationKeyVO.fromJson(json['specificationKeyVO'])
        : null;
    if (json['specificationValueVOList'] != null) {
      specificationValueVOList = new List<SpecificationValueVOList>();
      json['specificationValueVOList'].forEach((v) {
        specificationValueVOList.add(new SpecificationValueVOList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.specificationKeyVO != null) {
      data['specificationKeyVO'] = this.specificationKeyVO.toJson();
    }
    if (this.specificationValueVOList != null) {
      data['specificationValueVOList'] =
          this.specificationValueVOList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SpecificationKeyVO {
  String name;
  num id;
  num sort;
  num status;

  SpecificationKeyVO({this.name, this.id, this.sort, this.status});

  SpecificationKeyVO.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    sort = json['sort'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['id'] = this.id;
    data['sort'] = this.sort;
    data['status'] = this.status;
    return data;
  }
}

class SpecificationValueVOList {
  String name;
  num id;
  num specificationKeyId;
  num sort;
  num status;
  Null picture;

  SpecificationValueVOList(
      {this.name,
      this.id,
      this.specificationKeyId,
      this.sort,
      this.status,
      this.picture});

  SpecificationValueVOList.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    specificationKeyId = json['specificationKeyId'];
    sort = json['sort'];
    status = json['status'];
    picture = json['picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['id'] = this.id;
    data['specificationKeyId'] = this.specificationKeyId;
    data['sort'] = this.sort;
    data['status'] = this.status;
    data['picture'] = this.picture;
    return data;
  }
}
